"""Add resumes table for Milestone 3

Revision ID: c39b5241294d
Revises: 
Create Date: 2026-09-23 18:19:22.114582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c39b5241294d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('is_active_version', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('parsed_status', sa.String(length=20), nullable=False),
    sa.Column('parsed_text', sa.Text(), nullable=True),
    sa.Column('extracted_skills', sa.JSON(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.add_column('jobs', sa.Column('experience_level', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('fresher_friendly', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('jobs', sa.Column('low_competition', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('jobs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_experience_level'), 'jobs', ['experience_level'], unique=False)
    op.create_index(op.f('ix_jobs_fresher_friendly'), 'jobs', ['fresher_friendly'], unique=False)
    op.create_index(op.f('ix_jobs_low_competition'), 'jobs', ['low_competition'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_low_competition'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_fresher_friendly'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_experience_level'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_column('jobs', 'created_at')
    op.drop_column('jobs', 'low_competition')
    op.drop_column('jobs', 'fresher_friendly')
    op.drop_column('jobs', 'experience_level')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_table('resumes')
    # ### end Alembic commands ###
